CREATE TABLE debtor_statements (
  id INT AUTO_INCREMENT PRIMARY KEY,
  supplier VARCHAR(128) NOT NULL,
  date DATE NOT NULL,
  description VARCHAR(128) NOT NULL,
  debit DECIMAL(15,2) DEFAULT 0,
  credit DECIMAL(15,2) DEFAULT 0,
  balance DECIMAL(15,2) DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
