CREATE TABLE purchase_returns (
  id INT AUTO_INCREMENT PRIMARY KEY,
  returnNo VARCHAR(32) NOT NULL,
  supplier VARCHAR(128) NOT NULL,
  date DATE NOT NULL,
  reason VARCHAR(128) NOT NULL,
  amount DECIMAL(15,2) DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
