CREATE TABLE IF NOT EXISTS branches (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  code VARCHAR(100) NOT NULL,
  address VARCHAR(255),
  tel VARCHAR(50),
  manager VARCHAR(100),
  active BOOLEAN DEFAULT 1
);
